## Lab Tasks
1. Create a 1D array of integers from 1 to 20. Reshape it into a 4x5 2D array, 
then replace all elements in the last column with zeros. Finally, flatten the 
array back to 1D and print the result.

In [83]:
import numpy as np

arr = np.arange(1,21)
print("Array:",arr)
print()
arr1 = np.reshape(arr, (4, 5))
print("Reshaped: ",arr1)
print()
arr1[:,-1] = 0
print("Last column 0:",arr1)
arr2 = arr1.flatten()
print()
print("Flatten array:",arr2)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Reshaped:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Last column 0: [[ 1  2  3  4  0]
 [ 6  7  8  9  0]
 [11 12 13 14  0]
 [16 17 18 19  0]]

Flatten array: [ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


2. Generate a 2D array of random integers between 10 and 50 with a shape of 
5x5. Calculate and print the mean, sum, minimum, and maximum values for 
each row and each column separately.


In [85]:
arr = np.random.randint(10,50,size = (5,5))
print("Original Array: " ,arr)
print()
print('Row wise')
print()
print("Mean:",np.mean(arr, axis = 0))
print("maximum:",np.max(arr,axis = 0))
print("Sum",np.sum(arr, axis = 0))
print("Minimum",np.min(arr,axis = 0))
print()
print('Column wise')
print()
print("Mean",np.mean(arr, axis = 1))
print("Maximum",np.max(arr,axis = 1))
print("Sum",np.sum(arr, axis = 1))
print("Minimum",
      np.min(arr,axis = 1))

Original Array:  [[24 34 26 19 31]
 [35 39 49 37 43]
 [39 49 40 48 10]
 [35 42 24 21 44]
 [15 11 28 47 34]]

Row wise
[29.6 35.  33.4 34.4 32.4]
[39 49 49 48 44]
[148 175 167 172 162]
[15 11 24 19 10]
Column wise
[26.8 40.6 37.2 33.2 27. ]
[34 49 49 44 47]
[134 203 186 166 135]
[19 35 10 21 11]


3. Create an identity matrix of size 4x4. Add a constant (e.g., 5) to each 
element in the diagonal, and then replace the last row with a row of ones. 
Print the final matrix.


In [86]:
arr = np.identity(4,dtype = int)

arr = arr * 5
arr[3] = 1
print(arr)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [1 1 1 1]]


4. Generate a 1D array of 15 random integers between 0 and 20. Count and 
display the number of occurrences of each unique value in the array, and list 
the indices of elements greater than 10

In [79]:
arr = np.random.randint(0,20,size = (1,15))
print(arr)
arr1,count = np.unique(arr,return_counts = True)
print("unique:",arr1) 
print('count', count)
n , m = np.where(arr>10)
print("greater than 10", m)

[[11 14 11 11 13 16 15  2 14  2  5 15 10  2 19]]
unique: [ 2  5 10 11 13 14 15 16 19]
count [3 1 1 3 1 2 2 1 1]
greater than 10 [ 0  1  2  3  4  5  6  8 11 14]


5. Create a 3x4 array filled with random floating-point numbers between 0 and 
1 . Round each element to two decimal places, replace the elements in the 
second column with 0.5, and print the modified array.

In [57]:
arr = np.random.random(size = (3,4))
arr1 = np.round(arr,2)
arr1[:,1] = 0.5
arr1

array([[0.11, 0.5 , 0.02, 0.32],
       [0.94, 0.5 , 0.93, 0.4 ],
       [0.08, 0.5 , 0.7 , 0.19]])