## Lab 2


### TASK 1
You are processing player statistics for a sports analytics application. 
1. Create a NumPy array for player statistics (heights, weights, points scored). 
2. Update the weight of the player with the maximum points scored. 
3. Append a new player's statistics to the array. 
4. Insert a new statistic at a specified index within the array. 
5. Delete the player with the lowest points scored

In [49]:
import numpy as np
arr = np.random.randint(1,50,(10,3),dtype= np.uint8)
print("Original Array: ",arr)
# print(arr2)

Original Array:  [[43 20 23]
 [43 10 39]
 [37  1  2]
 [ 4 46 11]
 [40  1 46]
 [40 24 40]
 [ 7  7 30]
 [ 9 46 28]
 [20  6 42]
 [ 2 39  9]]


In [54]:
maximum = np.max(arr[:,2])
mask = np.where(arr[:,2] == maximum)
arr
arr[mask,1] = 51
arr


array([[43, 20, 23],
       [43, 10, 39],
       [37,  1,  2],
       [ 4, 46, 11],
       [40, 51, 46],
       [40, 24, 40],
       [ 7,  7, 30],
       [ 9, 46, 28],
       [20,  6, 42],
       [ 2, 39,  9]], dtype=uint8)

In [55]:
arr1 = np.append(arr,[[10,12,18]],axis = 0)
print("After appending:",arr1)

After appending: [[43 20 23]
 [43 10 39]
 [37  1  2]
 [ 4 46 11]
 [40 51 46]
 [40 24 40]
 [ 7  7 30]
 [ 9 46 28]
 [20  6 42]
 [ 2 39  9]
 [10 12 18]]


In [56]:
arr2 = np.insert(arr,1,[[10,12,18]],axis = 0)
print()
print("After insertion")
print(arr2)


After insertion
[[43 20 23]
 [10 12 18]
 [43 10 39]
 [37  1  2]
 [ 4 46 11]
 [40 51 46]
 [40 24 40]
 [ 7  7 30]
 [ 9 46 28]
 [20  6 42]
 [ 2 39  9]]


In [53]:
minimum = np.min(arr[:,2])
mask = np.where(arr[:,2] == minimum)
print(mask)
arr3 = np.delete(arr,mask,axis = 0)
print("After deletion")
print(arr3)

(array([2]),)
After deletion
[[43 20 23]
 [43 10 39]
 [ 4 46 11]
 [40 51 46]
 [40 24 40]
 [ 7  7 30]
 [ 9 46 28]
 [20  6 42]
 [ 2 39  9]]


### Task 2:  
Scenario: You are analyzing customer purchases. 
1. Create two NumPy arrays for purchase amounts and item counts. 
2. Create a shallow copy of one and a deep copy of the other. 
3. Concatenate both arrays. 
4. Split the concatenated array based on a condition. 
5. Modify the original arrays and analyze the effects on the copies. 

In [81]:
purchase = np.random.randint(1,50,10)
item_counts = np.random.randint(1,50,10)
shallow = purchase.view()
deep = item_counts.copy()
concatenated_array = np.concatenate((purchase,item_counts))
print("Concatenated Array:",concatenated_array)
print()

mask = concatenated_array > 15
splited_array1 = concatenated_array[mask]
splited_array2 = concatenated_array[~mask]

print("Splited Arrays:",splited_array2,splited_array1)
print()
shallow[5] = 10
print("Shallow Copy:",shallow,"Purchase",purchase)
print()
deep[5] = 51
print("Deep Copy: ",deep,"Item counts:",item_counts)

Concatenated Array: [33 11 32 34 37 24 29 17 42 11 41 49 19 46 21 36 30 45  4 33]

Splited Arrays: [11 11  4] [33 32 34 37 24 29 17 42 41 49 19 46 21 36 30 45 33]

Shallow Copy: [33 11 32 34 37 10 29 17 42 11] Purchase [33 11 32 34 37 10 29 17 42 11]

Deep Copy:  [41 49 19 46 21 51 30 45  4 33] Item counts: [41 49 19 46 21 36 30 45  4 33]


#### Bonus Task: Advanced Git Commands 
Scenario: You are working on a collaborative project and need to manage your changes 
effectively. Answer the following questions related to Git commands. 
1. Write down the Git command that allows you to temporarily save your uncommitted 
changes without committing them. Explain a situation in which this command would 
be useful during development. 
2. After you have temporarily saved your changes, how would you view the list of saved 
changes? Provide the command you would use. 
3. You decide that you want to reapply the most recent saved changes back to your 
working directory. Which command would you use for this operation, and what 
happens to the saved changes after you do this? 
4. If you want to remove a specific saved change entry after you have reapplied it, which 
command would you use? What should you consider before executing this command?

stash
status
